apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspire-gateway
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inspire-gateway
  template:
    metadata:
      labels:
        app: inspire-gateway
    spec:
      containers:
        - name: inspire-gateway
          image: uhub.service.ucloud.cn/entropypool/inspire-gateway:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/InspireGateway
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: inspire-gateway-config
            items:
              - key: service-conf
                path: InspireGateway.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: inspire-gateway
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50390
      targetPort: 50390
    - name: grpc
      port: 50391
      targetPort: 50391
    - name: healthz
      port: 50392
      targetPort: 50392
    - name: prometheus
      port: 50393
      targetPort: 50393
  selector:
    app: inspire-gateway
