apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: inspire-gateway-traefik-app-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: inspire-gateway-traefik-app
    k8s.kuboard.cn/workload: inspire-gateway-traefik-app
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-strip-inspire-gateway-prefix@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/inspire/v1/version
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
    - host: api.procyon.vip
      http: *http_rules
    - host: api.xpool.top
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.procyon.xpool.top
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: inspire-gateway-traefik-app-user-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: inspire-gateway-traefik-app-user
    k8s.kuboard.cn/workload: inspire-gateway-traefik-app-user
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-strip-inspire-gateway-prefix@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-user-role-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          ######
          # Enable to all users
          ######
          - path: /api/inspire/v1/get/goodarchivements
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          - path: /api/inspire/v1/get/commissionhistories
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          - path: /api/inspire/v1/get/app/commissions
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          - path: /api/inspire/v1/create/commission
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          - path: /api/inspire/v1/create/user/commission
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          - path: /api/inspire/v1/get/registrationinvitations
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          - path: /api/inspire/v1/update/registrationinvitation
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          - path: /api/inspire/v1/get/app/registrationinvitations
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          - path: /api/inspire/v1/create/invitationcode
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          - path: /api/inspire/v1/get/invitationcodes
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          - path: /api/inspire/v1/get/app/invitationcodes
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          - path: /api/inspire/v1/update/commission
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          #######
          # Only enable to app admin
          #######
          - path: /api/inspire/v1/update/archivement
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          - path: /api/inspire/v1/get/user/goodarchivements
            backend:
              serviceName: inspire-gateway
              servicePort: 50390
          
    - host: api.procyon.vip
      http: *http_rules
    - host: api.xpool.top
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.procyon.xpool.top
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
